import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import RouteLoader from "@/components/RouteLoader"; // 👈 Add this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NeoShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Orbitron:wght@400..900&display=swap" rel="stylesheet"></link>
      </head>
      <body className="flex flex-col min-h-screen bg-black">
        <RouteLoader /> {/* 👈 Add this to track route changes */}
        <Navbar />
        <main className="flex-grow pt-16">{children}</main>
        <Footer />
        <Toaster
          toastOptions={{
            style: {
              background: "rgba(17, 24, 39, 0.9)",
              color: "#fff",
              border: "1px solid rgba(99, 102, 241, 0.5)",
              boxShadow: "0 0 10px rgba(79, 70, 229, 0.5)",
            },
            success: {
              style: {
                border: "1px solid rgba(45, 212, 191, 0.5)",
                boxShadow: "0 0 10px rgba(45, 212, 191, 0.5)",
              },
            },
            error: {
              style: {
                border: "1px solid rgba(239, 68, 68, 0.5)",
                boxShadow: "0 0 10px rgba(239, 68, 68, 0.5)",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
